name: tests
on: pull_request
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Go
      uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: '1.18'
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
  codeql:
    name: analyze
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: go
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
  build:
    name: build test
    runs-on: ubuntu-latest
    needs:
    - golangci
    - codeql
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Go
      uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: '1.18'
    - name: Run go build
      run: |
        GOOS=${{matrix.goos}} GOARCH=${{matrix.goarch}} go build -v
